
GET http://localhost:3000/
###

POST http://localhost:3000/games 

###

DELETE  http://localhost:3000/games/1
###

DELETE http://localhost:3000/games/deleteall
###

PATCH  http://localhost:3000/games/1
###

GET http://localhost:3000/games/1